### ISSUE TITLE
Pull pre-defined templates to editing space

### ISSUE THREAD

**Issue by illarterate** [rawles/teletext-editor#1]
Not really an issue, more of a feature request. I know it's possible because I've seen it in the alpha versions:

Press a button to bring up a pre-defined template. We can design these - they just need adding to the editor.

Priority - medium? Not a massive issue as a say. Feel free to move this post if it's in the wrong place.

Dan

**Comment by rawles** [comment]
Can you be more specific about what you mean by 'template' here? If it's just a predefined screen, that can be loaded by loading a URL from your bookmarks. What special behaviour would a template exhibit? For example, are the character cells locked to prevent accidental editing?

**Comment by illarterate** [comment]
That's pretty much it, Simon - it just works the same as how you implemented Fluffy Duck in the test version you showed me. If we can replace those with a blog template etc., that would be great. 

Locked character cells sound like a great idea, yes!

**Comment by rawles** [comment]
Fluffy Duck is a test frame for held graphics, but I might have used it in another context. Can you explain?

**Comment by illarterate** [comment]
When you demoed an earlier version of the editor, you could hit a link to pull up a preloaded page for editing. All we need is a few of these for the templated pages... football match reports, blog posts and so on. ;)

**Comment by rawles** [comment]
Ah, yes. This was just a bookmark for the frame itself, since the data for the frame is in the URL. By adding information about which character cells are locked to the URL, we could have a sort of template, in that only some cells are (in some mode) editable. The template can then be passed around like any other editor frame, i.e. as a URL.

Since each character is in the range 0x00..0x7f, we can add locked cells without making the URL even longer by just setting the most significant bit if the cell is locked. A user could then lock or unlock cells and switch between 'template mode' and 'free mode'.

**Comment by illarterate** [comment]
OK, sounds good to me. :)

**Comment by rawles** [comment]
Locked cells were never implemented, but the original goal of this bug is now possible with the introduction of the editor as a JavaScript 'object' on which functions can be called. Now, you can add onload attributes to the HTML, containing calls to load(), with an encoded page. In this case the page would be the template you're talking about. Since it's now possible, I'm closing the bug.
