### ISSUE TITLE
Integrate URL shortener

### ISSUE THREAD

**Issue by Deltafire** [rawles/teletext-editor#27]
Other web sites I've used that store data in the URL sometimes have a handy shortcut for retrieving a shortened URL using one of the many services available for this.  Useful for passing links around.

**Comment by rawles** [comment]
Other people have suggested the same idea, but I'm hesitant. URL shorteners [have their shortcomings](http://joshua.schachter.org/2009/04/on-url-shorteners), and users can (and do) do the shortening themselves, easily, with their favourite shortener, taking responsibility for the shortcomings and risks when doing so.

I could set up a domain to help make the URLs more permanent, so that there's a single domain at which we can always rely on to have the editor page and JavaScript source. Of course, anyone else is welcome to do the same. The shortener could sit at the same domain, but I'm not convinced we'd be achieving anything by doing that.

**Comment by rawles** [comment]
What do others feel about this?

**Comment by illarterate** [comment]
I didn't realise URL shorteners had hidden dangers, to be honest. I probably should know better, as a one-time Geocities Baron of the Linkrot... :P

I haven't found a social media platform that doesn't auto shorten the long links when you paste them, at least not yet. Chalk that up as another point for not having a dedicated URL shortener...

**Comment by rawles** [comment]
I think social networks like to have shorteners because it enables them to better track the browsing behaviours of web users, making it easier to advertise things to them. In contrast, our editor is designed to be as private as possible. In particular, the part of the URL after the hash never appears in any server logs or anything like that.

**Comment by rawles** [comment]
There is now an integrated URL shortener which I wrote just for edit-tf. I figured that if the shortener lived and died with the editor, and didn't do any nasty tracking, then it didn't suffer from the shortcomings we've discussed.

The shortener also produces an image of the page which can be linked to with a very predictable URL.

The URLs it produces are public, and indeed, we may publish a list of the ID to URL mapping. Therefore, users should *not* shorten a frame unless they wish to consider it published.

Let me know how you get on!

**Comment by pjfdirect** [comment]
The URL shortener is brilliant: a super useful addition that people can and will make use of immediately. Filling the internet with pages 480px wide breaks my heart. Well that's a bit dramatic - I'll see if I can walk the talk and share an graphicsmagick example or sommat for resize. Great stuff!

**Comment by pjfdirect** [comment]
I did a search for 'gif' in the code but wasn't able to find it – so I don't know how you're making the GIFs. Apologies in advance if some of this isn't usable:

* Presumably you start with a set of 3-bit pixels arranged 480x500
* the width you, A, P & I all researched as 'typical' is the same 576 that is the edit.tf default now.
* height remains at 500
* is ideally performed in a non-indexed larger colour space but since by default the editor just adds a px of width to intermittent pixels to total 576, widening the image in the 8-colour colorspace is probably fine
* as I'm not sure how the GIFs are being generated, I don't know using graphicksmagick makes any sense. There may be a much simpler lib that can do the deed.

Changing an image in one or more steps is called 'mogrify' in graphicksmagick:
http://www.graphicsmagick.org/mogrify.html#mog-exam

If you use node.js here's a helper:
http://aheckmann.github.io/gm/
