### ISSUE TITLE
Hold Graphics difference vs BBC Micro Teletext mode

### ISSUE THREAD

**Issue by kieranhj** [rawles/teletext-editor#65]
The following frame was auto-generated from a JPG using my slightly dodgy image conversion tool which has a tendency to produce weird sequences of Hold Graphics / Release Graphics (yeah, need to fix my own bugs.)

http://edit.tf/#0:LoECBAgQIECBAgQIECBAgQIECBAgQIECDAcQIECBAgQIECAugQIECBAgQcD3AigQE8DBAgQIECBAgQIEBxAgQIECBAgQIC6BAgPEfBM6gQIC__f_OnP5P4gQIECBAgQHECBAgQIECBAgLoEB4iqOl8HD4T_nTh04dOFzpzqwQE8DBAcQIECBAgQIECAugQIECD901f_h0n_Onjh04dOHTjVASRr0pxAgQIECBAgQIC6BAgQav71UdQICZ1AgI4Nn8meLnPvTggUHECBAgQIECBAgLoECBAi_oUCo6gJnSPz7wQfTpdX_ZotfU4cQIECBAgQIECAugQIEBHl_4ICas6R_fzp44dJnThcj_Jl-pxAgQIECBAgQICa88lwHSP859_L1_86cOnDpw6cOnDpw6cJHECBAgQIECBAgJ42BH-dPHOyVGgQa17_X_OnDpw6cOnP5MkcQIECBAgQIECAnwI6v508c_9d_1Bq_7zqBAgQIECBAfLnH5xAgQIECBAgQICRdLobkf508c_sECr-dOHTh04dOHTh04ULnECBAgQIECBAgJF9X4j_Pd06Ff9wfzpw6cOnDpw6cOnDpQkcQIECBAgQIECAkhIpTpIieOIECD1_OnDpw6cOnDpw6cOnGBxAgQIECBAgQICX8jqOk2CBocQEf____________t_6FEvJHECBAgQIECBAgJoiO86gQE9Jwj6____________-lXklGpwcQIECBAgQIECAmX9Ef55q7_pUH7__7-Ha9evXp0aAkiQE0hxAgQIECBAgQICaJel4evqBAeInS_jr_OcEGjwgQIOBFAgJnECBAgQIECBAgJosTAjr_tC-Dh8_nv6JugPolBZGiX7__wmcQIECBAgQIECAnvRNdSAvx_fzz9OhQIFuBAgQIECAlgLIyZxAgQIECBAgQIC6BAg1ff39-nI6tRTAgQcECBAgQEkWtqjSnECBAgQIECBAgJHi_j-Wfp0B8jq9F9X_c1IsECBAgQIEB4ucQIECBAgQIECAvh_P_6dAgQICPr-X1f35HUlQIECBAgQHi5xAgQIECBAgQIC__-_I9daBAgQfzxfA_I_yS9GgQIECBAfLnECBAgQIECBAgLf06Ai3ffUCDUdPFC_VAfdHECBASWIECAocQIECBAgQIECA

It looks "correct" in edit.tf but has some black / blank characters when displayed on a BBC Micro in MODE 7 (Teletext.)  These can be seen in the attached photo:

![bbc_parrot_gaps](https://cloud.githubusercontent.com/assets/17362752/22080267/d69d8ab6-ddb6-11e6-9b9c-88570db26b25.jpg)

It would be great to find out what's going on here as I'm using edit.tf as my reference!

**Comment by ZXGuesser** [comment]
It looks like the hold mosaic character is only being set by mosaics occurring after the hold code.

**Comment by philpem** [comment]
If true, the ETSI Teletext standard (ETS 300 706) says that's not intended behaviour.

Hold Mosaic displays the most recent mosaic character; it doesn't matter if Hold is on or not. The test pattern in the appendices make that pretty clear.

(Not judging, I made the same mistake in my Viewtext/Teletext Level 1 renderer)

Mode 7 on a BBC isn't technically Teletext (as I understand it)... it's pre-ETSI so MODE7 having differences with TTX doesn't surprise me.

**Comment by ZXGuesser** [comment]
Yep it's an SAA5050 specific hardware thing. This issue should have been closed ages ago really.

**Comment by lurkio** [comment]
Sorry for commenting on a closed issue, but I was wondering whether there was a programmatic way to "fix" the compatibility issues that make edit.tf exports look wrong in MODE7? 

I exported [this pic](http://edit.tf/#9:KHS_BBgYIOCDAwQcEGBgROkECBGjRo0CBAgPEECBAgRo1e8odLoFiBQkQLEChIgWIEBc6RQIESNGjQoECBAgQIECBEjX_yh0uj4IsLBHwRYWCPgiQkTpdAgQIkaNGgQIECBAgQIEaNf_KHS6xAoSIFiBQkQLEChIXOkUCBAgRI0aBAgQIECBAgQI1a8odL8EeBkh4I8DJDwR4GBE6XQIECBAiRo0CBAgQIECBGrX_yh0ugWIFCRAsQKEiBYgQFzpJAgQIDxFEjQHiKBAgQIESNf_KHS6NAiQoEaBEhQI0CJCROkkCBAgPF0CNAeLoECBAgRo168udJIECBAgQIECBAgQIECBAgQIECA8RQKUCBAeIoECBEjX7yJ0kgQIECBAgQIECBAgQIECBAgQIDxDA2QIECA8XQIkatf_LnSSBAgQIECBAgQIECBAgQIECBAgPENX1AgQIDxFAgRo1_8idJIECBAgQYGCBAgQIECBAgQIECA8QQO0CBAgPF0CNGrX7y50kgQIECBAg__enBAgQIECBAgQIMHDx8fIECA8RQI0a9f_InSSBAgQIECD_____vTgTwePhLh-__zxE6XQIDxdAjRr1_8udJIMCBBtYINf88c_9v54mdJfv54kdL6P_88XOkUCNGv3_SJ0kgQK_ir6gRfzxz-_79_-9_3PEjpHB___zxE6XRI1a_f9LIEBJBw5bf7BBq77_qdGgRb_6cigJK0KBAgQICKBGjXr__8sgQEnyPf__pUCBG94Ed6gl-_kVyolmaIECBAgQcGCBAgIoiyBAR9EkGr8lQIPH75_-fPaNvp-fP3__9QIEGh-n8P8LBAgLIEBfeSQYnyBAg9v06H5___fv_-9yItL9AgL6fxJehXoECAsgQEVRJBqaoECBVvYNi6pCrRp05LW8QoECAui3oN7L-gQICyBASQIMH5Bw4MECBCr2dCPj30JaH6FBo68ECBAgLoUSFAgLIEBJAg_ff__u_QoGHxAj37PnzYnQeNTTeX_EkHjz_ToECAsgQEkGB-jRI0KtA20f_7TU2_70CB81foUCH5_QP0KBAgQICyBASQIkCBAgQIECDM-__ODNej4fnyBAgQIESHZ8XoUCBAgLIEBJAgQIECBAgQIEHb9____n__-QIECBAgQIESdAgQIECA), and then processed it using url2raw.pl. I then removed the newlines from the exported file and imported it into BeebEm and displayed it in MODE7. It doesn't quite look right. I suspect the discrepancy is due to what's been discussed in this Issue thread..? But I'm no MODE7/Teletext expert! 

Can the output from url2raw.pl be hacked in some way so that it displays correctly in MODE7? 

(I've attached a screenshot of how the exported pic appears in BeebEm.) 

<img width="640" alt="Screenshot 2020-12-26 at 22 49 51" src="https://user-images.githubusercontent.com/26767174/103160416-c04b6880-47cc-11eb-8a3d-88915ecaa995.png">

**Comment by ZXGuesser** [comment]
One problem is that the image uses foreground black which isn't supported by the BBC micro's mode 7.

**Comment by lurkio** [comment]
> One problem is that the image uses foreground black which isn't supported by the BBC micro's mode 7.

I see. So that probably explains the top right-hand corner of the flag, which is red in MODE7 but black in edit.tf..? Also the black "rip" in the flag is green in MODE7 for the same reason..?

But could the weird "twisting" of the yellow patch at the top of the Gremlin's head be corrected to look right in MODE7?

And what about the transparent "holes" on the right-hand edge of the Gremlin's left ear?

**Comment by ZXGuesser** [comment]
It might not be possible to re-order the control codes to fix the hold mosaics. As explained above it's a limitation of the hardware. I'm not at my PC to have a fiddle around with the page at the moment.
